name: Android CI

on:
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main
  workflow_dispatch:

jobs:
  build:
    if: contains(github.event.head_commit.message, '[deploy]')
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Check for deploy commit
      if: contains(github.event.head_commit.message, '[deploy]')
      id: deploy_check
      run: |
        if ! git log -1 --pretty=%B | grep -E '\[deploy\]'; then
          echo "Skipping build"
          exit 0
        fi

    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: gradle

    - name: Install Android SDK
      uses: android-actions/setup-android@v2
      with:
        api-level: 30
        build-tools: 30.0.3

    - name: Grant execute permission for gradlew
      run: chmod +x calculate_tip_app/gradlew

    - name: Build with Gradle
      run: |
        cd calculate_tip_app
        ./gradlew assembleDebug

    - name: List APK Directory
      run: ls -la calculate_tip_app/app/build/outputs/apk/debug

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: calculate_tip_app-debug-apk
        path: calculate_tip_app/app/build/outputs/apk/debug/app-debug.apk

  release:
    if: contains(github.event.head_commit.message, '[deploy]')
    needs: build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
      with:
        tag_name: 'v1.0.${{ github.run_number }}'
        release_name: 'Release v1.0.${{ github.run_number }}'
        draft: false
        prerelease: false

    - name: Download APK Artifact
      uses: actions/download-artifact@v3
      with:
        name: calculate_tip_app-debug-apk
        path: dist/

    - name: Rename APK
      run: mv dist/app-debug.apk dist/calculate_tip_app.apk

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: dist/calculate_tip_app.apk
        asset_name: business_card.apk
        asset_content_type: application/vnd.android.package-archive
